// TODO : Add more keywords related to Aelluminate Campus
export const keywords = [
  "Business",
  "Services",
  "IT Services",
  "Web Development",
  "SEO",
  "Data Analysis",
  "Marketing",
  "B2B",
  "SaaS",
  "Consulting",
  "Aelluminate",
  "Aelluminate Business Services",
  "Digital Transformation",
  "E-commerce Solutions",
  "Mobile App Development",
  "Project Management",
  "Business Intelligence",
  "Customer Relationship Management",
  "Enterprise Solutions",
  "Software Development",
  "Technology Consulting",
  "IT Support",
  "Data Management",
  "Business Strategy",
  "Innovation",
  "Tech Solutions",
  "Digital Marketing",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Lead Generation",
  "Market Research",
  "Brand Strategy",
  "User Experience",
]